name: Build browser zips

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2) Install Node for the manifest processing step
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # 3) Install system tools required by the Makefile
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y jq zip rsync

      # 4) Build the extension zips
      - name: Build all
        run: make all

      # 5) Read the version from the normalized manifest
      - name: Read version
        id: version
        run: |
          VERSION=$(jq -r '.version' dist/base/manifest.json)
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      # 6) Upload the versioned zip files
      - name: Upload artifacts
        env:
          VERSION: ${{ steps.version.outputs.version }}
        uses: actions/upload-artifact@v4
        with:
          name: extension-zips-v${{ env.VERSION }}
          path: |
            strike-tracker-chrome-v${{ env.VERSION }}.zip
            strike-tracker-firefox-v${{ env.VERSION }}.zip
          if-no-files-found: error
