name: Build browser zips

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) pull repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2) node is required for npx strip-json-comments-cli
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # 3) system deps used by Makefile
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y jq zip rsync

      # 4) run the Makefile (produces zips at repo root)
      - name: Build all
        run: make all

      # 5) capture version from the normalized manifest
      - name: Read version
        id: version
        run: |
          VERSION=$(jq -r '.version' dist/base/manifest.json)
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      # 6) upload artifacts; use version in the artifact name
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: extension-zips-v${{ env.VERSION }}
          path: |
            strike-tracker-chrome-v${{ env.VERSION }}.zip
            strike-tracker-firefox-v${{ env.VERSION }}.zip
          if-no-files-found: error
